defaults:
  - mppi: panda_push
  - isaacgym: push

goal: [0.5, 0.4, 0.7]
render: true
n_steps: 10
urdf_file: "panda_isaac/robots/franka_panda_stick.urdf"
ee_link: "panda_ee_tip"
fix_base: true
flip_visual: true
disable_gravity: true
nx: 14
