defaults:
  - mppi: boxer
  - isaacgym: push

goal: [2.0, 2.0]
initial_position: [1.0, 4.0, 0.1]
render: true
n_steps: 1000
urdf_file: "boxer/boxer.urdf"
fix_base: false
flip_visual: false
nx: 4
differential_drive: true
wheel_radius: 0.08
wheel_base: 0.314
wheel_count: 2
