defaults:
  - mppi: pointbot
  - isaacgym: normal

goal: [2.0, 2.0]
initial_position: [0.0, 0.0, 0.05]
render: true
n_steps: 1000
urdf_file: "point_robot.urdf"
fix_base: true
flip_visual: false
nx: 6
