defaults:
  - mppi: omnipanda
  - isaacgym: push

goal: [0.5, 0.4, 0.7]
render: true
n_steps: 10
urdf_file: "omni_panda/omniPandaWithGripper.urdf"
ee_link: "panda_link7"
fix_base: true
flip_visual: true
disable_gravity: true
nx: 24
