defaults:
  - mppi: panda
  - isaacgym: slow

goal: [0.5, 0.4, 0.7]
render: true
n_steps: 1000
urdf_file: "panda_isaac/robots/franka_panda.urdf"
ee_link: "panda_link7"
fix_base: true
flip_visual: true
nx: 14
